FROM authelia/authelia:4

# Copy the configuration file to the container.
COPY configuration.yml /config/configuration.yml
COPY users_database.yml /config/users_database.yml
COPY private.pem /config/private.pem
